name: Lint Code
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Markdown linting
      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**/*.md'
      
      # Bash linting
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
